### ISSUE TITLE
[1일] 회원 가입을 할 수 있습니다.

### ISSUE THREAD

**Issue by dhgudehd98** [ssg-java3-240304/spring-or-death#10]
## 🌈 Success criteria
1. db를 구축합니다. sh계정으로 springdb에 테이블/샘플데이터를 추가합니다.
2.springboot프로젝트에 웹어플리케이션에 알맞은 starter키워드를 선택하세요.
3. /app 인덱스페이지를 확인할 수 있습니다.
4. /regist 회원가입폼 페이지를 통해 회원가입을 처리합니다.
5. 이메일 중복확인을 비동기로 처리합니다.
6. 다음 상황에서는 폼이 제출되어서는 안됩니다.
7. 이메일 중복확인을 하지 않은 경우
8. 비밀번호가 일치하지 않은 경우
9. 필수 입력값이 작성되지 않은 경우
10. 이메일 중복확인을 하지 않은 경우
비밀번호가 일치하지 않은 경우
필수 입력값이 작성되지 않은 경우

## 🍳 Todo
- [x] 이메일 중복확인 테스트 코드 작성
- [x] 이메일 중복확인 Controller, Service, Mapper 작성 및 연결
- [x] 이메일 중복확인 로직 작성 
- [x] 회원 가입 테스트 코드 작성 
- [x] 회원 가입 Controller, Service, Mapper 작성 및 연결 
- [x] 이메일 중복 확인 로직 작성 -> 비동기처리 
- [x] 필수 입력값이 작성되지 않은 경우 데이터 저장 못하게 하기
