### ISSUE TITLE
[1일] 회원가입할 수 있습니다.

### ISSUE THREAD

**Issue by tjpark312** [ssg-java3-240304/spring-or-death#14]
# 🌈 Success criteria
1. db를 구축합니다. sh계정으로 springdb에 테이블/샘플데이터를 추가합니다.
2. springboot프로젝트에 웹어플리케이션에 알맞은 starter키워드를 선택하세요.
3. `/app` 인덱스페이지를 확인할 수 있습니다.
4. `/regist` 회원가입폼 페이지를 통해 회원가입을 처리합니다.
5. 이메일 중복확인을 비동기로 처리합니다.
6. 다음 상황에서는 폼이 제출되어서는 안됩니다.
  - 이메일 중복확인을 하지 않은 경우
  - 비밀번호가 일치하지 않은 경우
  - 필수 입력값이 작성되지 않은 경우

# 👷To-do
- [x] <추가 할일을 작성하고 실행합니다.>
- [x] controller, service, mapper 작성
- [x] input tag로 입력된 유저 정보 DB로 들어가는 코드 작성 후 DB에 정보 들어갔는지 확인해보기..
- [x] 이메일 중복 확인하는 코드 작성해보기....
- [x] 비밀번호 일치한지 확인하는 코드 작성해보기...

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.> 

정보 입력
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237157/fb8ffb35-bdc2-44b2-a419-24a1827bdc58)

![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237157/70e21990-facb-47e2-b748-ae0f6bacadc4)

이메일 중복 확인
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237157/ce122cb0-0366-4b6c-adee-cb06d69ba0d7)

![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237157/b4632903-14de-4a1b-9ce0-924d184356dc)

비밀 번호 일치 확인 

![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237157/023dd02c-bce0-4629-b7d0-87999be98477)

![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237157/1d92e5a2-6829-47b7-818a-c6ec0b8d3842)

폼 제출 막는건 하지 못하였습니다
