### ISSUE TITLE
[1일] 회원가입할 수 있습니다.

### ISSUE THREAD

**Issue by Hong-ji-min** [ssg-java3-240304/spring-or-death#15]
# 🌈 Success criteria
1. db를 구축합니다. sh계정으로 springdb에 테이블/샘플데이터를 추가합니다.
2. springboot프로젝트에 웹어플리케이션에 알맞은 starter키워드를 선택하세요.
3. `/app` 인덱스페이지를 확인할 수 있습니다.
4. `/regist` 회원가입폼 페이지를 통해 회원 가입을 처리합니다.
5. 이메일 중복확인을 비동기로 처리합니다.
6. 다음 상황에서는 폼이 제출되어서는 안됩니다.
  - 이메일 중복확인을 하지 않은 경우 → **비동기 처리**
  - 비밀번호가 일치하지 않은 경우 - **html내부에서 처리**
  - 필수 입력값이 작성되지 않은 경우 → **html에서 required 속성 사용**
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/39724768/0a75ea68-68e4-4288-8f89-2d974c30ce58)

# 🍒To-do
- [x] mvc 흐름으로 파일 구조 만들기
- [x] MemberDto, MemeberRegistDto 분리
- [x] 회원가입 시, 필수 입력값 처리
- [x] 회원가입 시,  DB 반영 확인
- [x] 이메일 중복 확인 처리
- [x] 비밀번호 일치 하지 않은 경우, 회원가입 안되도록 처리

# 👓 Review
### 1. sh계정으로 db 구축 & 샘플 데이터 추가
![image](https://github.com/Hong-ji-min/spring-or-death/assets/80135858/52884e0b-c1a6-45aa-ae0e-06d2c763eba5)
<br>

### 2. springboot프로젝트에 웹어플리케이션에 알맞은 starter키워드를 선택 
![image](https://github.com/Hong-ji-min/spring-or-death/assets/80135858/87c23794-2390-47c7-8a80-6d5717673358)
- 필요한 dependencies 추가했음
<br>

### 3. 인덱스 페이지 확인
<img width="562" alt="image" src="https://github.com/Hong-ji-min/spring-or-death/assets/80135858/980b26be-43f1-411a-9ba0-0b1d8ffe0309">
<br>

### 4. 필수 입력값 처리
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/5506600a-aa19-4707-b6f4-793ffa05187c)
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/2d91cd2e-fad3-43d2-864a-2e602fc2ac6e)
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/6edf9e86-0349-42ec-a48a-5cbfb445f4ff)
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/d90865f3-5580-407a-9d04-55ec4010f0de)
<br>

### 5. 회원가입시, DB 반영 확인
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/0fa19123-d490-4380-8942-749a3e4b934c)
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/d7cca174-eed9-4c59-a402-4c29f2ea745e)

### 6. 이메일 중복체크 처리 기능 추가
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/683401c3-6a13-49b4-b72a-9494669ba856)
- 이메일 중복처리 버튼 눌렀을때, DB에서 존재하는 이메일이면 "이미 사용중인 이메일입니다", 존재하지 않는 이메일이면 "사용가능한 이메일입니다"가 뜨게 처리
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/a9ae4958-70cd-4153-9584-a61fa4853150)
- 이메일 중복 체크를 하지 않고 제출을 할 경우, 이메일 중복체크를 먼저 하라는 메세지를 띄움
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/5d014be9-5b82-46ab-8a6f-64199c57606d)
- 이메일 중복처리를 한 후, 제출을 한 경우 회원 가입 성공했다는 메세지가 뜨게 처리
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/3fb8a69c-42ba-48c8-bee5-9f25a72213c9)
- 회원가입 완료 후, 메인 페이지로 redirect 처리

### 7. 비밀번호 일치하지 않은 경우, 폼 제출 처리 막기
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/feffb442-b4f6-476b-88c9-adebac61d60d)

**Comment by Hong-ji-min** [comment]
### html input태그에서 입력된 값을 변수로 사용하는 방법..?
```
const memberEmail = document.getElementById('email');
        alert(memberEmail);
        $.ajax({
            url: '[[@{/member/sameEmailCheck}]]',
            method: 'post',
            data: {
                memberEmail: **memberEmail**
```

![image](https://github.com/ssg-java3-240304/spring-or-death/assets/80135858/3cadf2c8-1ca1-41eb-9457-c9b07d167778)
- 이 코드에서 **memberEmail**만 쓸 경우, 값을 받는 것이 아니라 object 자체를 찍어버림 -> 따라서 memberEmail.value로 써야 함!
