### ISSUE TITLE
[1일] 회원가입할 수 있습니다.

### ISSUE THREAD

**Issue by jeonhyeonseon** [ssg-java3-240304/spring-or-death#19]
# 🌈 Success criteria
1. db를 구축합니다. sh계정으로 springdb에 테이블/샘플데이터를 추가합니다.
2. springboot프로젝트에 웹어플리케이션에 알맞은 starter키워드를 선택하세요.
3. `/app` 인덱스페이지를 확인할 수 있습니다.
4. `/regist` 회원가입폼 페이지를 통해 회원가입을 처리합니다.
5. 이메일 중복확인을 비동기로 처리합니다.
6. 다음 상황에서는 폼이 제출되어서는 안됩니다.
  - 이메일 중복확인을 하지 않은 경우
  - 비밀번호가 일치하지 않은 경우
  - 필수 입력값이 작성되지 않은 경우
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/39724768/0a75ea68-68e4-4288-8f89-2d974c30ce58)

# 👷To-do
- [x] springdb sh계정에 추가하기
- [x] 이메일 중복확인하지 않은 경우
- [ ] 비밀번호 일치하지 않은 경우
- [x] 필수 입력값이 작성되지 않은 경우

# 👓 Review
1. 필수 입력값이 작성되지 않은 경우
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237209/bb930787-081e-4997-be4b-d7e8aad5c36d)

2. 회원가입 db에 등록 
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237209/b0a7c3a2-5b00-4c69-bcf6-53de4e3000ec)

3. 이메일 중복 체크
![스크린샷 2024-07-10 233807](https://github.com/ssg-java3-240304/spring-or-death/assets/162237209/47c636e5-bef8-43ac-9159-6b110209c2a4)

**Comment by jeonhyeonseon** [comment]
중복체크 버튼을 눌렀을 때 alert메시지 창이 나오지 않는다. 
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237209/542a2573-d4ce-438f-b19c-edb730847422)
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237209/55f550dd-29e8-4216-b6dd-67e767209474)
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162237209/4732cadd-dbe0-445b-9b3d-e5ea1980139b)
1. application.yaml 작성이 제대로 되었는지 확인하기
2. controller에서 post방식으로 작성할 경우 반환 값 제대로 확인하기
3. ajax, 자바스크립트 공부가 더 필요함
