### ISSUE TITLE
[1.5일] 사용자 프로필 사진 업로드를 포함해 회원가입할 수 있습니다.

### ISSUE THREAD

**Issue by Hong-ji-min** [ssg-java3-240304/spring-or-death#20]
# 🌈 Success criteria
1. 구현한 회원 가입에 추가 요구 사항이 발생했습니다
2. 회원 가입 시에 사용자 프로필 사진을 업로드할 수 있어야 합니다.
3. 회원 테이블에 적절한 profile 컬럼을 추가하고, 회원 가입 시에 업로드한 파일 경로(FTP서버의 파일 경로)를 저장합니다.
4. FTP파일 서버의 접속 계정은 `myftp/myftp`입니다.
5. 업로드한 파일 조회를 위한 url은 `http://ssg-java3.iptime.org/myftp/업로드한파일명` 입니다.

![Image](https://github.com/ssg-java3-240304/spring-or-death/assets/39724768/d8409ed3-50b9-4a50-a791-49890844507a)

# 🍒To-do
- [ ] FTP 파일 서버 접속 계정 설정하기
- [ ] 회원 테이블에 profile컬럼 추가
- [ ] 회원 가입 시에, 파일 경로 저장(ex. `http://ssg-java3.iptime.org/myftp/업로드한파일명` )

# 👓 Review
### 1. FTP 파일 서버 접속 계정 설정
![image](https://github.com/user-attachments/assets/a0fa9cea-0194-4b9e-a008-eb6597d7f4d2)

### 2. member 테이블에 profile 컬럼 추가
![image](https://github.com/user-attachments/assets/07e3a7aa-364e-4892-8049-f81fc4b51646)

### 3. 회원 가입 시에, 파일 경로 저장
![image](https://github.com/user-attachments/assets/7f1207d7-887f-4643-ab39-1c5316e017bf)

**Comment by Hong-ji-min** [comment]
## 🔥프로필 등록시, 해당 회원 Id에 맞게 등록
- 등록한 회원 Id에 맞게 프로필 경로를 등록해야하는데, 제출을 눌러야 회원이 DB에 저장됨
- 그러면 그 이후에 member_id가 부여되므로,,이 부분을 알아보기,,! 인데 일단 정처기,,,공부하러,,,갑니닷,,,,😂

**Comment by Hong-ji-min** [comment]
## ✨잊지 말것 
### 중간에 log를 찍어서 어디까지 성공했는 지를 보는 습관을 갖기!
