### ISSUE TITLE
[1.5일] 사용자 프로필 사진 업로드를 포함해 회원가입할 수 있습니다. 

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/spring-or-death#26]
# 🌈 Success criteria
1. 구현한 회원가입에 추가 요구사항이 발생했습니다
2. 회원가입시에 사용자 프로필 사진을 업로드할 수 있어야 합니다.
3. 회원 테이블에 적절한 profile 컬럼을 추가하고, 회원가입시에 업로드한 파일 경로(FTP서버의 파일 경로)를 저장합니다.
4. FTP파일서버의 접속 계정은 `myftp/myftp`입니다.
5. 업로드한 파일 조회를 위한 url은 `http://ssg-java3.iptime.org/myftp/업로드한파일명` 입니다.

![Image](https://github.com/ssg-java3-240304/spring-or-death/assets/39724768/d8409ed3-50b9-4a50-a791-49890844507a)

# 👷To-do
- [x] FileUploadService.java 작성
- [x] MemberDto, MemberRegistDto에 파일url컬럼인 profilepath컬럼 추가
- [x] Form태그에 파일업로드에 필요한 enctype="multipart/form-data" 추가
- [x] regist.html에 이미지 등록 div추가

# 👓 Review
### 1. member/regist 홈 화면
<img width="1429" alt="image" src="https://github.com/user-attachments/assets/cba9abcf-e0e9-4e57-9a8c-c83f93327403">

### 2. 회원가입 진행
<img width="1476" alt="image" src="https://github.com/user-attachments/assets/2b570bb9-cf75-4041-9852-dc8e903b786a">

### 3. DB 회원가입 정보 업로드 성공
<img width="1530" alt="image" src="https://github.com/user-attachments/assets/1a151816-d029-439f-989c-dd9507c298f3">

### 4. FileZila 회원 사진 업로드 성공
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/45d63e9a-1a82-44d9-800b-dcf603c18f88">

**Comment by vlshzl35** [comment]
질문
1. ajax의 url을 하드코딩하지 않고 동적으로 쓰고싶은데 400 오류가 납니다.
url은 맞는 것 같은데 이유를 모르겠습니다. 타임리프가 아예 작동을 안합니다. 
<img width="650" alt="image" src="https://github.com/user-attachments/assets/7097ec7b-2b14-4026-ac5e-4d4b1afb21ac">

브라우저 경로 app/member/emailCheck
<img width="724" alt="image" src="https://github.com/user-attachments/assets/a511a28d-c50c-4fd3-b50f-0241e1d86bec">




2. redirectAttributes로 회원가입완료 message를 alert로 띄우고 싶습니다.
<img width="843" alt="image" src="https://github.com/user-attachments/assets/9e2f8477-77f3-46ad-ba25-2e6519acd87b">
이렇게 하는게 아닌가요? 
alert창에 ${messge}가 뜹니다. message값을 controller에서 가져오질 못합니다.

**Comment by vlshzl35** [comment]
## 질문

1. ajax의 url을 하드코딩하지 않고 동적으로 쓰고싶은데 400 오류가 납니다. url은 맞는 것 같은데 이유를 모르겠습니다. 
타임리프가 아예 작동을 안합니다. 
<img width="400" alt="image" src="https://github.com/user-attachments/assets/7097ec7b-2b14-4026-ac5e-4d4b1afb21ac">

브라우저 경로 app/member/emailCheck
<img width="400" alt="image" src="https://github.com/user-attachments/assets/a511a28d-c50c-4fd3-b50f-0241e1d86bec">

브라우저 에러 콘솔
<img width="600" alt="image" src="https://github.com/user-attachments/assets/752a9cad-5f3e-4f9a-89c1-82e9ef7049d2">


2. redirectAttributes로 회원가입완료 message를 alert로 띄우고 싶습니다.
<img width="400" alt="image" src="https://github.com/user-attachments/assets/9e2f8477-77f3-46ad-ba25-2e6519acd87b"><br>
이렇게 하는게 아닌가요? alert창에 ${messge}가 뜹니다. message값을 controller에서 가져오질 못합니다.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/aa46aeff-cbdd-4140-bed5-a711a6d801f7">

**Comment by shqkel** [comment]
https://github.com/ssg-java3-240304/spring-or-death/issues/26#issuecomment-2235584103
![Image](https://github.com/user-attachments/assets/492b65bf-16d6-454d-a0e8-b1728b748a33)
1. html페이지 내에 script태그로 작성하는 방법
2. html페이지 내 script태그에서 `const contextPath = '[[@{/}]]'` 작성후, js파일에서 ` url = contextPath + "/emailCheck"` 로 변수 참조하는 방법

**Comment by shqkel** [comment]
![Image](https://github.com/user-attachments/assets/ac8cf1b8-05fd-42c5-8db5-98b60c063cd4)

**Comment by vlshzl35** [comment]
[강사님 답변]
자바스크립트는 정적파일이라 타임리프가 적용되지 않는다. 보통 HTML의 <script>태그 안에 넣어야 타임리프가 적용되는데, js파일에 넣고 싶을 경우 <script>태그 안에 const로 변수를 만들어 값을 넣어주고, 
![image](https://github.com/user-attachments/assets/fdd9a757-261d-4838-b883-46d96ad756f4)
그 변수를 js에서 사용하는 식으로 구현해야 한다.

1. ajax url변경
![image](https://github.com/user-attachments/assets/53c8b506-b264-480c-aacb-4b1b1c0f4e3c)

2. redirectAttribute를 alert로 출력
폼 안에 alert를 넣게되면 다음 폼 제출 시 alert가 출력된다. 하지만 이미 폼제출을 한 상태이기때문에 위치가 맞지 않는다. form밖에 alert문을 넣어줘야 한다
![image](https://github.com/user-attachments/assets/c631273a-d7db-48cd-bdfe-5620add63f9b)
