### ISSUE TITLE
[1일] 회원가입할 수 있습니다

### ISSUE THREAD

**Issue by vlshzl35** [ssg-java3-240304/spring-or-death#4]
# 🌈 Success criteria
1. db를 구축합니다. sh계정으로 springdb에 테이블/샘플데이터를 추가합니다.
2. springboot프로젝트에 웹어플리케이션에 알맞은 starter키워드를 선택하세요. (모듈만들때 dependencies)
3. `/app` 인덱스페이지를 확인할 수 있습니다.
4. `/regist` 회원가입폼 페이지를 통해 회원가입을 처리합니다.
5. 이메일 중복확인을 비동기로 처리합니다.
6. 다음 상황에서는 폼이 제출되어서는 안됩니다.
  - 이메일 중복확인을 하지 않은 경우
  - 비밀번호가 일치하지 않은 경우
  - 필수 입력값이 작성되지 않은 경우
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/39724768/0a75ea68-68e4-4288-8f89-2d974c30ce58)

# 👷To-do
- [x]  DB구축
- [x]  /app, /regist 페이지 로딩
- [x]  이메일 중복 확인을 하지 않은 경우
- [x]  비밀번호가 일치하지 않은 경우
- [x]  필수 입력값이 작성되지 않은 경우

# 👓 Review
### 1. 이메일 중복 확인
사용가능할 경우
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/73ed0e1f-b7ed-4292-940e-652ce09fbbbc">

이미 사용중인 경우
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/6602acf6-5c03-456c-9d13-df808b4ac0cc">

### 2.이메일 중복 확인을 하지 않은 경우
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/a8953cfa-df30-45e2-9f62-573fde11b15d">

### 3.  비밀번호가 일치하지 않은 경우
비밀번호 aa, 비밀번호 확인 bb입력으로 비일치
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/16e14503-e692-4f48-99d3-745058faea79">

### 4. 필수 입력값이 작성되지 않은 경우
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/5e13679a-c642-42f9-9598-222d02546428">

### 회원가입 성공(폼 제출 성공시)
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/71be1b7f-4cf5-45aa-8dce-dd3539d5867b">

DB에 반영됐다
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/90a27043-31a7-48d2-8f9f-09dc3fbc3cf1">

이메일 중복처리도 된다
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/b6a13f42-dbcd-47d8-a3de-0399709e202d">

**Comment by vlshzl35** [comment]
이메일 중복확인 버튼을 누르면 계속 400에러가 뜹니다
<img width="894" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/7f353d35-9258-44df-a7fc-95e5f950dd6e">

1. controller
` // 이메일 중복체크
    @GetMapping("/emailCheck")
    public int emailCheck(@RequestParam String email){
        log.info("클라이언트에서 이메일 받음",email);
        return memberQueryService.checkDuplicatEmail(email); // 중복이면 1, 중복이 아니면 0리턴
    }`

**Comment by vlshzl35** [comment]
이메일 중복확인 버튼을 누르면 계속 400에러가 뜹니다
emailCheck버튼과 @getmapping이 연결이 안되는 것 같은데 이유를 모르겠습니다

<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/11134d39-c78d-408e-a3b9-60ba710c2bad">


1. controller
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/20c9409b-cf29-40ef-ae9e-9e47e5f33e14">

2. html의 폼속성, 이메일 중복검사 버튼 속성
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/bdf6db34-39a7-4238-ae03-71ef300e3f81">

3. regist.js
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/63b48b16-f7bd-4c1b-97fc-690ce019e65d">

**Comment by vlshzl35** [comment]
mapper에서 중복일 경우 1,  중복이 아닐 경우 0을 반환해서 mvc를 int로 받았습니다.
Controller에 @ResponseBody를 넣지 않으니 이 오류가 뜹니다. 
<img width="400" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/7211695e-17a3-418c-b78f-35983f5cfcc8">


정수 자료형 그대로 반환하는 것이 맞는것 아닌가요? 왜 Integer로 바꿔서 줘야하는지 모르겠습니다.
console.log(response.type)이 undefined로 나와 확인을 못했습니다.

<img width="500" alt="image" src="https://github.com/ssg-java3-240304/spring-or-death/assets/81032378/d17f5612-e6ca-4467-b8f8-866bdf5e5344">

@ResponseBody는 메서드가 반환하는 값의 타입에 따라 적절한 형태로 변환하여 클라이언트에게 전달하는 역할이라 
알아서 리턴시에 현재 필요한 자료형(Integer)으로 매칭시켜주어 @ResponseBody를 붙혔을때 코드가 정상적으로 작동되는 것인가요?

**Comment by shqkel** [comment]
https://github.com/ssg-java3-240304/spring-or-death/issues/4#issuecomment-2217262111

`@ResponseBody` 가 없다면 반환값을 view Name으로 인식하게 됩니다.
`@ResponseBody`를 작성한다면, 반환값을 직접 Http 응답메세지 본문에 작성하는 것이고요 😄

**Comment by vlshzl35** [comment]
강사님 Review
- [ ]  Regist.js에 ajax url 하드코딩 한것 바꾸기
- [ ] 중복인지 아닌지를 mapper에서 0,1로 받은후, controller에서 중복O, 중복X를 쉽게 확인할 수 있도록 변수로 선언해서 js에게 보내준다. 
     js는 그 변수명을 비교하도록 바꾼다. 내 regist.js에 강사님이 comment달아놓으심 참고할 것
