### ISSUE TITLE
[1일] 회원가입할 수 있습니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/spring-or-death#9]
# 🌈 Success criteria
1. db를 구축합니다. sh계정으로 springdb에 테이블/샘플데이터를 추가합니다.
2. springboot프로젝트에 웹어플리케이션에 알맞은 starter키워드를 선택하세요.
3. `/app` 인덱스페이지를 확인할 수 있습니다.
4. `/regist` 회원가입폼 페이지를 통해 회원가입을 처리합니다.
5. 이메일 중복확인을 비동기로 처리합니다.
6. 다음 상황에서는 폼이 제출되어서는 안됩니다.
  - 이메일 중복확인을 하지 않은 경우
  - 비밀번호가 일치하지 않은 경우
  - 필수 입력값이 작성되지 않은 경우
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/39724768/0a75ea68-68e4-4288-8f89-2d974c30ce58)

# 👷To-do
- [x] db를 구축합니다. sh계정으로 springdb에 테이블/샘플데이터를 추가합니다.
- [x] springboot프로젝트에 웹어플리케이션에 알맞은 starter키워드를 선택하세요.
- [x] `/app` 인덱스페이지를 확인할 수 있습니다.
- [x] `/regist` 회원가입폼 페이지를 통해 회원가입을 처리합니다.
- [x] 이메일 중복확인을 비동기로 처리합니다.
- [x] 다음 상황에서는 폼이 제출되어서는 안됩니다.
  - 이메일 중복확인을 하지 않은 경우
  - 비밀번호가 일치하지 않은 경우
  - 필수 입력값이 작성되지 않은 경우

# 👓 Review
1. db 구축 완료
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162238064/c75b5cd7-eeec-4c1c-a7be-d2be263082a4)

2. 회원가입 처리 완료 
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162238064/3148cf8b-3855-4944-8234-9c29e17c2d7a)

**Comment by nnieun** [comment]
![image](https://github.com/ssg-java3-240304/spring-or-death/assets/162238064/304b8b86-59cd-4a62-9568-5a7cf9a0711b)
제출버튼을 누르면 404에러가 뜨는중 입니다,,
-> html 에서 action을 잘못 썼습니다. 또 mapper에서 오타났습니다
